# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - prac1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: ''

      - name: Install Python dependencies
        run: |
          python -m venv env
          .\\env\\Scripts\\activate
          pip install -r requirements.txt

      - name: Zip the application files
        run: Compress-Archive .\\* app.zip
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'prac1'
          slot-name: 'Production'
          package: '.\\app.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CD7BE2819D944A80A5A4003FC6039679 }}